SET IDENTITY_INSERT [dbo].[Profissao] ON

INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ADMINISTRADOR ', 1)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ADMINISTRADOR DE EDIFICIO ', 2)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ADMINISTRADOR DE EXPLORACAO AGRICOLA ', 3)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ADMINISTRADORES ', 4)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ADVOGADO ', 5)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ADVOGADO DIREITO DO TRABALHO ', 6)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AGENCIADOR DE PROPAGANDA ', 7)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AGENTE ADMINISTRATIVO ', 8)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AGENTE DE COMPRAS ', 9)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AGENTE DE VENDA DE SERVICOS AS EMPRESAS ', 10)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AGENTE DE VIAGEM ', 11)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AGENTE PUBLICITARIO ', 12)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AGENTE TECNICO DE VENDAS ', 13)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AGENTES ADMINISTRATIVOS ', 14)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AGENTES DE ADMINISTRACAO DE EMPRESAS PUBLICAS E PRIVADAS ', 15)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ALMOXARIFE ', 16)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE CARGOS E SALARIOS ', 17)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE COMERCIALIZACAO ', 18)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE COMUNICACA 8234    ANALISTA DE CREDITO E COBRANCA ', 19)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE IMPORTACAO E EXPORTACAO ', 20)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE OCUPACAO ', 21)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE ORGANIZACAO E METODOS ', 22)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE PESQUISA DE MERCADO ', 23)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE RECURSOS HUMANOS ', 24)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE SEGUROS ', 25)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE SISTEMAS ', 26)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ANALISTA DE SUPORTE DE SISTEMA ', 27)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('APONTADOR DE MAO DE OBRA ', 28)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('APONTADOR DE PRODUCAO ', 29)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ARQUITETO ', 30)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ARQUIVISTA ', 31)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ASSISTENTE ADMINISTRATIVO ', 32)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ASSISTENTE DE PATRIMONIO ', 33)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ASSISTENTE DE VENDAS FINANCEIRO ', 34)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ASSISTENTE SOCIAL ', 35)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ATENDETE DE ENFERMAGEM ', 36)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ATLETA PROFISSIONAL DE FUTEBOL ', 37)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUDITOR CONTABIL ', 38)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUDITOR GERAL ', 39)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE ALMOXARIFADO ', 40)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE BIBLIOTECA ', 41)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE CONTABILIDADE ', 42)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE ENFERMAGEM ', 43)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE ESCRITORIO ', 44)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE FARMACIA ', 45)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE IMPORTACAO E EXPORTACAO ', 46)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE LABORATORIO DE ANALISES CLINICAS ', 47)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE LABORATORIO DE ANALISES FISICOQUIMICAS ', 48)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE PESSOAL ', 49)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE SEGUROS ', 50)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIAR DE SERVICOS JURIDICOS ', 51)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIARES DE CONTABILIDADE ', 52)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('AUXILIARES DE ESCRITORIO ', 53)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('BABA ', 54)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('BARMAN ', 55)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('BIBLIOTECARIO ', 56)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('BIOLOGISTA ', 57)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('BIOQUIMICO ', 58)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CABELEIREIRO ', 59)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CARTEIRO ', 60)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE ADMINISTRATIVOS ', 61)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE ALMOXARIFADO ', 62)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE CONTABILIDADE ', 63)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE CONTABILIDADE E FINANCAS ', 64)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE CONTAS A PAGAR ', 65)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE CONTROLE DE PATRIMONIO ', 66)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE ESCRITORIO ', 67)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE ESCRITORIO CONTABILIDADE ', 68)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE ESCRITORIO CREDITO E COBRANCA ', 69)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE ESCRITORIO ORCAMENTO ', 70)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE ESCRITORIO PESSOAL ', 71)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE ESCRITORIO SERVICOS GERAIS ', 72)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE ESCRITORIO TESOURARIA ', 73)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE RECEPCAO HOTEL ', 74)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE SERVICO DE TRANSPORTE RODOVIARIO ', 75)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CHEFE DE SERVICOS DE TELECOMUNICACOES ', 76)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CIRURGIAO ', 77)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CIRURGIAO DENTISTA ', 78)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CODIFICADOR DE DADOS ', 79)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('COMERCIANTE VAREJISTA ', 80)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('COMISSARIO DE BORDO AERONAVES ', 81)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('COMPRADOR COMERCIO ATACADISTA E VAREJISTA ', 82)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CONDUTOR DE CAMINHAO BASCULANTE ', 83)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CONDUTORES DE AUTOMOVEIS ', 84)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CONSULTOR JURIDICO ', 85)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CONTADOR ', 86)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CONTRAMESTRE DE EMBARCACAO ', 87)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CONTRAMESTRE INDUSTRIA TEXTIL ', 88)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('COORDENADOR DE ENSINO ', 89)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CORRESPONDENTE COMERCIAL ', 90)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('COZINHEIRO CHEFE ', 91)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('CRONOANALISTA ', 92)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DATILOGRAFO ', 93)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DEMONSTRADOR ', 94)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DESENHISTA ', 95)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DESENHISTA PROJETISTA ', 96)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DESENHISTA TECNICO ', 97)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DESPACHANTE ', 98)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIAGRAMADOR ', 99)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIGITADOR ', 100)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE EMPRESA ', 101)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE EMPRESA DE COMERCIO VAREJISTA ', 102)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE EMPRESA DE COMUNICACOES ', 103)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE EMPRESA DE CONSTRUCAO CIVIL ', 104)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE EMPRESA DE PRESTACAO DE SERVICOS ', 105)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE EMPRESA DE SERVICOS CLINICOS E HOSPITALARES ', 106)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE EMPRESA FINANCEIRA ', 107)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE EMPRESA MANUFATUREIRA ', 108)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE ESTABELECIMENTO DE ENSINO ', 109)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETOR DE ESTABELECIMENTO DE ENSINO SUPERIOR ', 110)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('DIRETORES DE EMPRESAS ', 111)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ECONOMISTA ', 112)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ECONOMISTA MERCADOLOGIA ', 113)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ECONOMISTA PROGRAMACAO ECONOMICO FINANCEIRA ', 114)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ECONOMISTAS ', 115)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('EDITOR DE LIVROS ', 116)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENCARREGADO DE DIGITACAO E OPERACAO ', 117)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENFERMEIRO ', 118)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENFERMEIRO DO TRABALHO ', 119)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENFERMEIROS ', 120)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO AERONAUTICO ', 121)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO AGRONOMO ', 122)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO CIVIL ', 123)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO DE CONTROLE DE QUALIDADE ', 124)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO DE MANUTENCAO ELETRICIDADE E ELETRONICA ', 125)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO DE MINAS ', 126)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO DE ORGANIZACAO E METODOS ', 127)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO DE SEGURANCA DO TRABALHO ', 128)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO DE TELECOMUNICACOES ', 129)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO DE TRAFEGO ', 130)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO ELETRICISTA ', 131)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO ELETRONICO ', 132)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO MECANICO ', 133)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIRO QUIMICO ', 134)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ENGENHEIROS ', 135)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ESCRITURARIO ', 136)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ESCRIVAO ', 137)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ESTATISTICO ', 138)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ESTETICISTA ', 139)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('FARMACEUTICO ', 140)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('FISIOTERAPEUTA ', 141)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('FONOAUDIOLOGO ', 142)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('FUNCIONARIO PUBLICO ESTADUAL SUPERIOR ', 143)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('FUNCIONARIO PUBLICO FEDERAL SUPERIOR ', 144)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('FUNCIONARIO PUBLICO MUNICIPAL SUPERIOR ', 145)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('FUNCIONARIO PUBLICO SUPERIOR ', 146)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GEOLOGO ', 147)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE ADMINISTRATIVO ', 148)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE COMERCIAL ', 149)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE BANCO ', 150)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE BAR ', 151)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE COMPRA ', 152)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE  EMPRESAS ', 153)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE HOTEL ', 154)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE INFORMATICA ', 155)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE LOJA ', 156)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE MARKETING ', 157)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE OPERACAO ', 158)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE PESQUISA E DESENVOLVIMENTO ', 159)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE PESSOAL ', 160)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE PLANEJAMENTO ', 161)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE POSTAL E TELECOMUNICACOES ', 162)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE PRODUCAO ', 163)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE PROPAGANDA ', 164)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE RESTAURANTE ', 165)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE RH ', 166)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE TRANSPORTE ', 167)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE DE VENDAS ', 168)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE EXECUTIVO ', 169)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE FINANCEIRO ', 170)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('GERENTE OPERACIONAL ', 171)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('INSPETOR DE PRODUCAO ', 172)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('INSPETOR DE QUALIDADE ', 173)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('INSPETOR DE	SERVICOS DE TRANSPORTE ', 174)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('INSPETOR TECNICO DE VENDAS ', 175)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('INSTRUTOR DE APRENDIZAGEM E TREINAMENTO ', 176)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('JORNALISTA ', 177)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('LABORATORISTA ANALISES CLINICAS ', 178)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('LABORATORISTA INDUSTRIAL ', 179)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('LOCUTOR ', 180)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MAITRE ', 181)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MEDICO ', 182)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MEDICO ANESTESISTA ', 183)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MEDICO CARDIOLOGISTA ', 184)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MEDICO DO TRABALHO ', 185)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MEDICO GINECOLOGISTA ', 186)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MEDICO ORTOPEDISTA ', 187)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MEDICO PEDIATRA ', 188)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MEDICO PSIQUIATRA ', 189)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MEDICO VETERINARIO ', 190)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MESTRE CONTRUCAO CIVIL ', 191)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MESTRE INDUSTRIAL ', 192)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MOTOCICLISTA TRANSPORTE DE MERCADORIAS ', 193)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MOTORISTA ', 194)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MOTORISTA DE CAMINHAO ', 195)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MOTORISTA DE FURGAO OU VEICULO SIMILAR ', 196)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MOTORISTA DE ONIBUS ', 197)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MOTORISTA DE TAXI ', 198)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('MUSICO ', 199)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('NUTRICIONISTA ', 200)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OPERADOR DE CAMERA DE TELEVISAO ', 201)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OPERADOR DE COMPUTADOR ', 202)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OPERADOR DE EQUIPAMENTOS DE ENTRADA DE DADOS ', 203)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OPERADOR DE ESTACAO DE RADIO ', 204)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OPERADOR DE MAQUINAS E VEICULOS ', 205)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OPERADOR DE MICRO ', 206)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OPERADOR DE PRODUTOS FINANCEIROS ', 207)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OPERADOR DE RAIOS X ', 208)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OPERADOR DE TELEMARKETING ', 209)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ORIENTADOR EDUCACIONAL ', 210)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('OURIVES ', 211)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PEDAGOGO ', 212)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PILOTO ', 213)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PINTOR ', 214)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PRODUTOR DE RADIO E TELEVISAO ', 215)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE 1A A 4A SERIE ENSINO DE 1O GRAU ', 216)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE ADMINISTRACAO ENSINO SUPERIOR ', 217)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE ALUNOS COM DEFICENCIAS MENTAIS ', 218)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE BIOLOGIA ENSINO DE 2O GRAU ', 219)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE CIENCIAS NATURAIS ENSINO DE 1O GRAU ', 220)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE COMUNICACAO ', 221)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE CONTABILIDADE ENSINO SUPERIOR ', 222)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE DIDATICA ENSINO SUPERIOR ', 223)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE DIREITO ', 224)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE ECONOMIA ', 225)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE EDUCACAO FISICA ', 226)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE ENFERMAGEM ', 227)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE ENSINO PRE ESCOLAR ', 228)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE ESTATISTICA ', 229)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE ESTUDOS SOCIAIS ENSINO DE 1O GRAU ', 230)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE FISICA ', 231)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE FISIOTERAPIA ENSINO SUPERIOR ', 232)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE HISTORIA ', 233)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE INGLES ', 234)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE LINGUA PORTUGUESA ', 235)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE LINGUAS ESTRANGEIRAS ', 236)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE MATEMATICA ', 237)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE ORIENTACAO EDUCACIONAL ENSINO SUPERIOR ', 238)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE PEDAGOGIA ', 239)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE PORTUGUES E LITERATURA ', 240)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE PRATICA DE ENSINO ENSINO SUPERIOR ', 241)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE PSICOLOGIA ', 242)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE QUIMICA ', 243)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE SOCIOLOGIA ', 244)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSOR DE TECNOLOGIA ', 245)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSORES ', 246)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSORES DE BIOLOGIA ', 247)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSORES DE CIENCIAS HUMANAS ', 248)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSORES DE ENSINO DE 2O GRAU ', 249)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSORES DE ENSINO DE PRIMEIRO GRAU ', 250)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSORES DE ENSINO ESPECIAL ', 251)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSORES DE ENSINO PRE ESCOLAR ', 252)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSORES DE ENSINO SUPERIOR ', 253)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSORES DE PEDAGOGIA ', 254)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROFESSSOR DE GEOGRAFIA ', 255)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROGRAMADOR DE COMPUTADOR ', 256)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PROPAGANDISTA DE PRODUTOS DE LABORATORIO ', 257)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('PSICOLOGO ', 258)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('QUIMICO ', 259)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('QUIMICO ANALISTA ', 260)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('QUIMICO INDUSTRIAL ', 261)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('RECEPCIONISTA ', 262)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('REDATOR ', 263)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('RELACOES PUBLICAS ', 264)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('REPORTER ', 265)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('REPRESENTANTE COMERCIAL ', 266)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SECRETARIO ', 267)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SECRETARIO BILINGUE ', 268)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SECRETARIO EXECUTIVO ', 269)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SERVENTUARIOS DA JUSTICA ', 270)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SOCIOLOGO ', 271)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SUPERVISOR DE COMPRAS ', 272)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SUPERVISOR DE VENDAS COMERCIO ATACADISTA ', 273)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SUPERVISOR DE VENDAS COMERCIO VAREJISTA ', 274)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SUPERVISOR EDUCACIONAL ', 275)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SUPERVISORES DE COMPRAS E COMPRADORES ', 276)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('SUPERVISORES DE VENDAS ', 277)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO ', 278)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO AGRICOLA ', 279)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO AGROPECUARIO ', 280)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE ADMINISTRACAO ', 281)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE CONTABILIDADE ', 282)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE ENFERMAGEM ', 283)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE LABORATORIO ', 284)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE MANUTENCAO ELETRICA ', 285)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE MANUTENCAO ELETRONICA ', 286)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE OBRAS CIVIS ', 287)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE PLANEJAMENTO DE PRODUCAO ', 288)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE SEGURANCA DO TRABALHO ', 289)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE SEGUROS ', 290)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO DE TELECOMUNICACOES ', 291)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO ELETRONICO ', 292)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO MECANICO ', 293)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO MECANICO MAQUINAS ', 294)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO METALURGICO ', 295)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICO QUIMICO ', 296)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICOS DE BIOLOGIA  ', 297)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICOS DE ELETRICIDADE ', 298)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICOS DE ENFERMAGEM ', 299)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TECNICOS DE OBRAS CIVIS ', 300)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TERAPEUTA OCUPACIONAL ', 301)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TOPOGRAFO ', 302)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TRABALHADORES DAS PROFISSOES CIENTIFICAS ', 303)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TRABALHADORES DE COMERCIO ', 304)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TRABALHADORES DE SERVICOS ADMINISTRATIVOS ', 305)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TRABALHADORES DE SERVICOS DE CONTABILIDADE ', 306)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('TRABALHADORES DE SERVICOS DE TURISMO ', 307)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('VENDEDOR A DOMICILIO ', 308)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('VENDEDOR AMBULANTE ', 309)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('VENDEDOR DE COMERCIO ATACADISTA ', 310)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('VENDEDOR DE COMERCIO VAREJISTA ', 311)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('VENDEDOR PRACISTA ', 312)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('VENDEDORES DE COMERCIO ATACADISTA E VAREJISTA ', 313)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('VENDEDORES PRACISTAS ', 314)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('VEREADOR ', 315)
INSERT INTO [dbo].[Profissao] ([Descricao], [ProfissaoID]) VALUES ('ZOOTECNISTA', 316)

SET IDENTITY_INSERT [dbo].[Profissao] OFF

