SET IDENTITY_INSERT [dbo].[Pais] ON

INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (1, 'AFG', 'PS', 'Afeganistão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (2, 'AFS', 'EN', 'África do Sul')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (3, 'AHL', 'NL', 'Antilhas Holandesas')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (4, 'ALB', 'SQ', 'Albânia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (5, 'ANB', 'EN', 'Antigua')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (6, 'AND', 'CA', 'Andorra')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (7, 'ANG', 'PT', 'Angola')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (8, 'ARA', 'AR', 'Arábia Saudita')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (9, 'ARG', 'ES', 'Argentina')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (10, 'ARL', 'ES', 'Argélia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (11, 'ARM', 'RU', 'Armênia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (12, 'ASM', 'EN', 'Samoa Americana')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (13, 'ATC', 'EN', 'Antartida')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (14, 'AUS', 'EN', 'Austrália')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (15, 'AUT', 'DE', 'Austria')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (16, 'AZE', 'RU', 'Azerbaijão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (17, 'BAR', 'AR', 'Barein')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (18, 'BEA', 'RU', 'Belarus')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (19, 'BEL', 'FR', 'Bélgica')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (20, 'BEN', 'EN', 'Benin')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (21, 'BER', 'EN', 'Bermudas')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (22, 'BGD', 'BN', 'Bangladesh')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (23, 'BHS', 'EN', 'Bahamas')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (24, 'BIR', 'BM', 'Birmânia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (25, 'BKF', 'FR', 'Burkina Fasso')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (26, 'BLZ', 'EN', 'Belize')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (27, 'BOL', 'ES', 'Bolívia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (28, 'BOS', 'EN', 'Bósnia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (29, 'BOT', 'EN', 'Botsuana')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (30, 'BRA', 'PT', 'Brasil')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (31, 'BRB', 'EN', 'Barbados')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (32, 'BRN', 'MS', 'Brunei')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (33, 'BUL', 'BG', 'Bulgária')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (34, 'BUR', 'FR', 'Burundi')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (35, 'BUT', 'DZ', 'Butão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (36, 'CAM', 'EN', 'Camarões')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (37, 'CAN', 'EN', 'Canadá')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (38, 'CAT', 'AR', 'Catar')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (39, 'CAZ', 'RU', 'Cazaquistão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (40, 'CBJ', 'KM', 'Camboja')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (41, 'CBV', 'PT', 'Cabo Verde')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (42, 'CCK', 'EN', 'Ilhas Cocos')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (43, 'CHA', 'FR', 'Chade')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (44, 'CHL', 'ES', 'Chile')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (45, 'CHN', 'ZH', 'China')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (46, 'CHP', 'EL', 'Chipre')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (47, 'CIN', 'EN', 'Cingapura')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (48, 'CMF', 'FR', 'Costa do Marfim')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (49, 'COK', 'EN', 'Ilhas Cook')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (50, 'COL', 'EN', 'Colômbia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (51, 'COM', 'EN', 'Comores')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (52, 'CON', 'FR', 'Congo')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (53, 'CRC', 'ES', 'Costa Rica')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (54, 'CRN', 'KO', 'Coréia do Norte')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (55, 'CRO', 'EN', 'Croácia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (56, 'CRS', 'KO', 'Coréia do Sul')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (57, 'CUB', 'ES', 'Cuba')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (58, 'CXR', 'EN', 'Christmas Island')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (59, 'CYM', 'EN', 'Ilhas Cayman')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (60, 'DIN', 'DA', 'Dinamarca')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (61, 'DJI', 'EN', 'Djibuti')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (62, 'DOM', 'ES', 'República Dominicana')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (63, 'DON', 'EN', 'Dominica')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (64, 'EAU', 'AR', 'Emirados Árabes')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (65, 'EGI', 'AR', 'Egito')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (66, 'ELS', 'ES', 'El Salvador')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (67, 'EQU', 'ES', 'Equador')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (68, 'ERT', 'AR', 'Eritréa')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (69, 'ESC', 'EN', 'Escócia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (70, 'ESH', 'EN', 'Western Sahara')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (71, 'ESP', 'ES', 'Espanha')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (72, 'EST', 'RU', 'Estônia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (73, 'ETP', 'AM', 'Etiópia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (74, 'EUA', 'EN', 'Estados Unidos')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (75, 'FIL', 'FL', 'Filipinas')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (76, 'FIN', 'EN', 'Finlândia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (77, 'FJI', 'EN', 'Fiji')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (78, 'FLK', 'EN', 'Ilhas Falkland')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (79, 'FOR', 'ZH', 'Formosa')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (80, 'FRA', 'FR', 'França')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (81, 'FSM', 'EN', 'Micronésia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (82, 'GAB', 'FR', 'Gabão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (83, 'GAL', 'EN', 'Gales')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (84, 'GAM', 'EN', 'Gâmbia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (85, 'GAN', 'EN', 'Gana')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (86, 'GBR', 'EN', 'Grã-Bretanha')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (87, 'GDL', 'FR', 'Guadalupe')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (88, 'GEO', 'RU', 'Geórgia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (89, 'GFR', 'FR', 'Guiana Francesa')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (90, 'GIB', 'EN', 'Gibraltar')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (91, 'GNB', 'PT', 'Guiné Bissau')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (92, 'GNE', 'ES', 'Guiné')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (93, 'GNQ', 'EN', 'Guiné Equatorial')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (94, 'GRD', 'EN', 'Granada')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (95, 'GRE', 'EL', 'Grécia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (96, 'GRL', 'EN', 'Groênlandia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (97, 'GUA', 'ES', 'Guatemala')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (98, 'GUI', 'EN', 'Guiana')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (99, 'GUM', 'EN', 'Guam')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (100, 'HKG', 'EN', 'Hong Kong')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (101, 'HOL', 'NL', 'Holanda')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (102, 'HON', 'ES', 'Honduras')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (103, 'HTI', 'FR', 'Haiti')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (104, 'HUN', 'HU', 'Hungria')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (105, 'IDN', 'IN', 'Indonésia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (106, 'IEM', 'AR', 'Iêmem')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (107, 'IFA', 'DA', 'Ilhas Faroe')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (108, 'IMH', 'EN', 'Ilhas Marshall')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (109, 'IMS', 'AR', 'Iêmen do Sul')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (110, 'IND', 'HI', 'Índia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (111, 'ING', 'EN', 'Inglaterra')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (112, 'IOT', 'EN', 'Britsh Indian Ocean')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (113, 'IRA', 'FA', 'Irã')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (114, 'IRL', 'EN', 'Irlanda')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (115, 'IRN', 'EN', 'Irlanda do Norte')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (116, 'IRQ', 'AR', 'Iraque')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (117, 'ISL', 'IS', 'Islândia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (118, 'ISR', 'IW', 'Israel')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (119, 'ITA', 'IT', 'Itália')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (120, 'IUG', 'SH', 'Iugoslávia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (121, 'IVA', 'EN', 'Ilhas Vírgens EUA')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (122, 'JAM', 'EN', 'Jamaica')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (123, 'JAP', 'JA', 'Japão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (124, 'JOR', 'AR', 'Jordânia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (125, 'KIR', 'EN', 'Kiribati')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (126, 'KNA', 'EN', 'São Cristóvão Nevis')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (127, 'KWT', 'AR', 'Kuweit')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (128, 'LAO', 'LO', 'Laos')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (129, 'LBN', 'AR', 'Líbano')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (130, 'LBR', 'EN', 'Libéria')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (131, 'LCA', 'EN', 'Santa Lúcia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (132, 'LES', 'EN', 'Lesoto')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (133, 'LET', 'RU', 'Letônia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (134, 'LIB', 'AR', 'Líbia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (135, 'LIE', 'DE', 'Liechtenstein')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (136, 'LIT', 'RU', 'Lituânia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (137, 'LUX', 'FR', 'Luxemburgo')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (138, 'MAC', 'PT', 'Macau')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (139, 'MAD', 'FR', 'Madagascar')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (140, 'MAL', 'MS', 'Malásia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (141, 'MAR', 'AR', 'Marrocos')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (142, 'MAU', 'EN', 'Maurício')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (143, 'MBQ', 'PT', 'Moçambique')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (144, 'MCD', 'MK', 'Macedônia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (145, 'MDV', 'EN', 'Maldivas')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (146, 'MEX', 'ES', 'México')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (147, 'MGL', 'MN', 'Mongólia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (148, 'MID', 'EN', 'Ilhas Midway')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (149, 'MLI', 'FR', 'Mali')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (150, 'MLT', 'MT', 'Malta')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (151, 'MLV', 'EN', 'Malavi')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (152, 'MMR', 'EN', 'Mianmar')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (153, 'MOL', 'RU', 'Moldova')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (154, 'MON', 'FR', 'Mônaco')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (155, 'MRT', 'FR', 'Martinica')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (156, 'MSR', 'EN', 'Montserrat')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (157, 'MTN', 'AR', 'Mauritânia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (158, 'NAM', 'EN', 'Namíbia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (159, 'NCL', 'FR', 'Nova Caledônia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (160, 'NFK', 'EN', 'Ilhas Norfolk')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (161, 'NGA', 'EN', 'Nigéria')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (162, 'NIC', 'ES', 'Nicarágua')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (163, 'NIG', 'FR', 'Niger')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (164, 'NIU', 'EN', 'Niue')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (165, 'NOR', 'NO', 'Noruega')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (166, 'NPL', 'NE', 'Nepal')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (167, 'NRU', 'EN', 'Nauru')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (168, 'NZL', 'EN', 'Nova Zelândia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (169, 'OMA', 'AR', 'Oma')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (170, 'PAN', 'ES', 'Panamá')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (171, 'PAQ', 'UR', 'Paquistão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (172, 'PCI', 'EN', 'Pacific Islands')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (173, 'PCN', 'EN', 'Pitcairn')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (174, 'PER', 'ES', 'Peru')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (175, 'PLF', 'FR', 'Polinésia Francesa')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (176, 'PLU', 'EN', 'Palau')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (177, 'PNG', 'EN', 'Papua Nova Guiné')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (178, 'POL', 'PL', 'Polônia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (179, 'POR', 'PT', 'Portugal')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (180, 'PRG', 'ES', 'Paraguai')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (181, 'PTR', 'ES', 'Porto Rico')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (182, 'QUE', 'SW', 'Quênia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (183, 'QUI', 'RU', 'Quirgistão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (184, 'RCA', 'FR', 'Rep.Centro-Africana')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (185, 'REU', 'FR', 'Reunião')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (186, 'RFA', 'DE', 'Alemanha')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (187, 'ROM', 'RO', 'Romênia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (188, 'RSS', 'RU', 'Rússia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (189, 'RUA', 'FR', 'Ruanda')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (190, 'SAM', 'EN', 'Samoa Ocidental')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (191, 'SEN', 'FR', 'Senegal')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (192, 'SHN', 'EN', 'Ilhas Santa Helena')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (193, 'SIR', 'AR', 'Síria')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (194, 'SLB', 'EN', 'Ilhas Salamão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (195, 'SMR', 'IT', 'San Marino')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (196, 'SOM', 'AR', 'Somália')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (197, 'SPM', 'EN', 'São Pedro Miquelon')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (198, 'SRI', 'SI', 'Sri Lanka')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (199, 'SRL', 'EN', 'Serra Leoa')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (200, 'STP', 'EN', 'São Tomé e Príncipe')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (201, 'SUA', 'EN', 'Suazilândia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (202, 'SUD', 'AR', 'Sudão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (203, 'SUE', 'SV', 'Suécia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (204, 'SUI', 'FR', 'Suiça')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (205, 'SUR', 'NL', 'Suriname')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (206, 'SVK', 'EN', 'Eslováquia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (207, 'SVN', 'EN', 'Eslovênia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (208, 'SYC', 'EN', 'Seychelles')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (209, 'TAD', 'RU', 'Tadjaquistão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (210, 'TAI', 'TH', 'Tailândia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (211, 'TAN', 'EN', 'Tanzânia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (212, 'TCA', 'EN', 'Ilhas Turcas Caicos')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (213, 'TCH', 'CS', 'República Tcheca')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (214, 'TGO', 'FR', 'Togo')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (215, 'TKL', 'EN', 'Tokelau')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (216, 'TMP', 'EN', 'Timor')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (217, 'TON', 'EN', 'Tonga')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (218, 'TRT', 'EN', 'Trinidad e Tobago')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (219, 'TUC', 'RU', 'Turcomenistão')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (220, 'TUN', 'AR', 'Tunísia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (221, 'TUR', 'TR', 'Turquia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (222, 'TUV', 'EN', 'Tuvalu')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (223, 'UCR', 'RU', 'Ucrânia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (224, 'UGA', 'EN', 'Uganda')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (225, 'URS', 'RU', 'União Soviética')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (226, 'URU', 'ES', 'Uruguai')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (227, 'UZB', 'RU', 'Uzbekistan')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (228, 'VAT', 'IT', 'Vaticano')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (229, 'VCT', 'EN', 'São Vicente Granadi')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (230, 'VEN', 'ES', 'Venezuela')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (231, 'VGB', 'EN', 'Ilhas Vírgens GBR')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (232, 'VTN', 'VI', 'Vietnã')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (233, 'VUT', 'EN', 'Vanuatu')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (234, 'WAK', 'EN', 'Ilhas Wake')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (235, 'WLF', 'EN', 'Ilhas Wallis Futuna')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (236, 'ZAN', 'EN', 'Zâmbia')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (237, 'ZAR', 'FR', 'Zaire')
INSERT INTO [dbo].[Pais] ([PaisID], [Sigla], [CodigoIdioma], [Descricao]) VALUES (238, 'ZIN', 'EN', 'Zimbabue')

SET IDENTITY_INSERT [dbo].[Pais] OFF
